Added the port-name of prometheus-data instead of prometheus in Prometheus Ingress
astronomer/astronomer pull request #1134
Opened 2021-06-22 22:21 UTC by rbankston

## Description

When using a newer k8s version the prometheus ingress port name isn't correct causing a 503 error because of the port name.

## 🎟 Issue(s)

Part of astronomer/issues#3126

## 🧪  Testing

Verified that my clusters prometheus page now works without manually changing the port name 

## 📸 Screenshots

Broken:

```
spec:
  rules:
  - host: prometheus.airflow.ralphbankston.com
    http:
      paths:
      - backend:
          service:
            name: uat-prometheus
            port:
              name: prometheus
        path: /
        pathType: Prefix
```
Fixed:

```
spec:
  rules:
  - host: prometheus.airflow.ralphbankston.com
    http:
      paths:
      - backend:
          service:
            name: uat-prometheus
            port:
              name: prometheus-data
        path: /
        pathType: Prefix
```
## 📋 Checklist

- [x] The PR title is informative to the user experience

2021-06-22 22:45 UTC, danielhoherd commented
@rbankston can we get a test for this? I can zoom with you if you want to go over how that might work.

2021-06-23 15:38 UTC, rbankston commented
@danielhoherd is there a test I didn't see from where this was added in https://github.com/astronomer/astronomer/pull/1122 ?

2021-06-23 22:11 UTC, danielhoherd commented on tests/test_prometheus_ingress.py
> +    def test_basic_ingress(self, kube_version):
```suggestion
    def test_prometheus_ingress(self, kube_version):
```

2021-06-23 22:12 UTC, danielhoherd requested changes
Oooh, this change is less complicated than I thought. For some reason I thought this would be different in different versions of k8s, but it's a prom component version thing. Cool. Thanks for adding test! Just one small change and this can be merged.

2021-06-24 14:21 UTC, rbankston commented
Yeah definitely not a big change but for k8s 1.20 and 1.21 makes the prometheus.basedomain usable. That change has been committed to change the name of the function

2021-06-24 18:38 UTC, merged