remove postgres init container
astronomer/astronomer pull request #1340
Opened 2022-01-18 15:37 UTC by pgvishnuram

## Description

we no longer need to run init container with root privileges for in cluster postgres , we have already migrated our postgres image to run as non root. we can disable this in astronomer/astronomer postgres chart helm values

## Related Issues

https://github.com/astronomer/issues/issues/4087

## Testing

NA

2022-01-18 20:33 UTC, danielhoherd requested changes
@pgvishnuram I'd like to see some tests with this.

Also, since we don't use this init container any more, do we even need it? Can we get rid of lines 48-68?

2022-01-19 09:13 UTC, pgvishnuram commented
I just thought of only disabling the init container configuration

2022-01-19 22:54 UTC, danielhoherd commented
> I just thought of only disabling the init container configuration

OK, that's fine, we can just leave it in place but disabled by default. Once there are tests we can merge this.

2022-01-24 15:37 UTC, pgvishnuram commented
@danielhoherd - is this test case is fine or you need to more validation

2022-01-24 15:40 UTC, pgvishnuram commented
@danielhoherd - is this test case is fine or you need to more validation

2022-01-24 16:11 UTC, danielhoherd commented
@pgvishnuram those tests are fine :) every little bit helps.

2022-01-24 16:12 UTC, danielhoherd approved these changes

2022-01-24 16:12 UTC, merged