Remove nginx metrics port from being exposed by the ingress load balancer.
astronomer/astronomer pull request #1404
Opened 2022-03-10 11:55 UTC by shmanu017

## Description

- Removed the following from the current service definition

```
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      name: metrics
```

- Created the following new separate Service and Network Policy definitions for Nginx metrics 
 

## Related Issues

https://github.com/astronomer/issues/issues/3040

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

2022-03-11 02:08 UTC, danielhoherd commented on tests/test_nginx_service.py
> +        print(f"port_names dict: {ports_by_name}")
This should be removed

2022-03-11 02:08 UTC, danielhoherd commented on tests/test_nginx_service.py
> +        NodeMetricsPort = 10254
This is defined but never used.

2022-03-11 02:10 UTC, danielhoherd commented on tests/test_nginx_service.py
> +from lib2to3.pgen2.token import EQUAL
This does not appear to be used... what even is this? Never seen it before, looks odd.

2022-03-11 02:16 UTC, danielhoherd requested changes
This looks like a good start. I get confused about the NetworkPolicy stuff I'd have to check those while the cluster was running to be sure. It would be great if we had functional tests for them, but we can work on that later.

The unit tests here need some work, but so far it's looking like a good start.

2022-03-11 03:15 UTC, shmanu017 commented on tests/test_nginx_service.py
> +        NodeMetricsPort = 10254
Added an asset to compare the port

2022-03-11 19:08 UTC, danielhoherd commented on tests/test_nginx_networkpolicy.py
> +class TestNginx:
```suggestion
class TestNginxNetworkPolicy:
```

2022-03-11 19:09 UTC, danielhoherd commented on tests/test_nginx_service.py
> +        assert doc["spec"]["ports"][0]["port"] == NodeMetricsPort
```suggestion
        doc = render_chart(
            show_only=["charts/nginx/templates/nginx-metrics-service.yaml"],
        )[0]
        assert doc["spec"]["type"] == "ClusterIP"
        assert doc["spec"]["ports"][0]["port"] == 10254
```

2022-03-16 20:18 UTC, danielhoherd approved these changes

2022-03-16 20:19 UTC, merged