nginx ingress controller enhancements
astronomer/astronomer pull request #1417
Opened 2022-03-21 13:20 UTC by pgvishnuram

## Description

* add electionID flag to nginx controller
* update values files for overrides

## Related Issues

Issue Link: https://github.com/astronomer/issues/issues/4392

## Testing

Need to update

2022-03-21 13:22 UTC, pgvishnuram commented
self note: add test cases to validate

2022-03-21 16:19 UTC, danielhoherd requested changes
This could use some tests, even if just to validate that the electionID value works as expected. These test cases could be included inside of other tests cases for defaults and custom configs.

2022-03-21 16:20 UTC, danielhoherd commented on charts/nginx/values.yaml
> +electionID: ingress-controller-leader
AFAIK camelCase has `election_id` as `electionId` <https://capitalizemytitle.com/camel-case/>
```suggestion
electionId: ingress-controller-leader
```

2022-03-21 17:30 UTC, danielhoherd commented
@pgvishnuram tests failed due to prometheus not being available, which is a known flaky test. Can you bump [test_prometheus_targets](https://github.com/astronomer/astronomer/blob/774cf23ae7/bin/functional-tests/test_config.py#L66) to `@pytest.mark.flaky(reruns=20, reruns_delay=10)` in this branch? Seems like it would be worth waiting a little bit longer rather than re-running the entire workflow.

2022-03-22 18:42 UTC, pgvishnuram commented
@danielhoherd - Yea added test case to validate election-id

2022-03-22 19:06 UTC, merged