Reduce Commander Permissions and fix namespace pools Houston config
astronomer/astronomer pull request #1429
Opened 2022-03-29 13:53 UTC by AmFlint

## Description

This PR contains:
- Reduce permissions for Commander
- Fix a bug, when using the new global.features.namespacePools value, the rendered configmap for Houston to use these preCreatedNamespaces was not formatted properly: I rendered a list of string, instead of a list of object with the form {"name": "namespace-name"}.

At the moment, users do not like the permissions we give to Commander:
- `*` values in permissions can be risky
- Permissions to manage ClusterRoles and ClusterRoleBindings is too dangerous, if someones steals commander's Service Account, he can just create an admin ClusterRole + binding and gain access to the whole cluster.

The only scenario in which we want to give Commander the permissions to manage Cluster* RBAC resources is if the user uses the Airflow multinamespace mode, see the official [Airflow chart](https://github.com/apache/airflow/blob/77d4e725c639efa68748e0ae51ddf1e11b2fd163/chart/templates/rbac/pod-launcher-role.yaml#L22).

So, in order to fix these problems, I removed `*` permissions (and added these permissions to each resource required by Commander instead), and only create the rules for commander to manage Cluster* RBAC resources if the option (multinamespace mode) is enabled in Airflow (users can customize Airflow chart values by providing these values when deploying this Astronomer chart in the [houston configuration](https://github.com/astronomer/houston-api/blob/5238c5e1ad3a87df8acc43f2b6ec07413a4b560b/config/default.yaml#L697)).

## Related Issues

- https://github.com/astronomer/issues/issues/4382 (Fix a bug I introduced in the PR https://github.com/astronomer/astronomer/pull/1407)
- https://github.com/astronomer/issues/issues/4332

## Testing

I'll add details on how to test this fix

2022-03-29 14:31 UTC, andriisoldatenko commented
@AmFlint can you please fix tests?

2022-03-30 14:15 UTC, andriisoldatenko approved these changes

2022-03-30 14:22 UTC, andriisoldatenko requested changes

2022-03-30 15:35 UTC, andriisoldatenko commented on charts/astronomer/templates/commander/commander-role.yaml
> +{{- if $.Values.houston.config.deployments.helm }}
sounds good.

2022-03-30 15:35 UTC, andriisoldatenko approved these changes

2022-03-30 17:39 UTC, danielhoherd approved these changes

2022-03-30 21:41 UTC, merged