kubestate metrics adding extra args
astronomer/astronomer pull request #1599
Opened 2022-07-11 10:56 UTC by pgvishnuram

* current kube state config does not allow us to provide extra args to allow additional flags, this change allow that option
* post 2.0.x kube-state version not all metrics are exposed by default to reduce load , this allow us to define args needed for platform to work

## Description

Do not merge this PR until this description is replaced with relevant info.

## Related Issues

Do not merge this PR until this text is replaced with links to related issues.

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

2022-07-11 10:58 UTC, santoshr1016 approved these changes
Lgtm

2022-07-11 14:02 UTC, pgvishnuram commented
@danielhoherd - is it possible to add this to 0.29.2

2022-07-12 01:17 UTC, danielhoherd requested changes
Looks good. Needs tests.

2022-07-20 16:18 UTC, vishwas-astro commented
@pgvishnuram can you add the tests to this and get this merged soon? I would like to include this in 0.30.0 release.

2022-07-27 06:40 UTC, santoshr1016 approved these changes
LGTM..

2022-07-27 18:53 UTC, danielhoherd commented on charts/kube-state/values.yaml
> +- --metric-labels-allowlist=namespaces=[*]
Just to make this a bit more clear and safe

```suggestion
- "--metric-labels-allowlist=namespaces=[*]"
```

2022-07-27 18:57 UTC, danielhoherd approved these changes

2022-07-28 07:14 UTC, merged