Included new parameter regionendpoint under s3 registry backend configuration
astronomer/astronomer pull request #1607
Opened 2022-07-19 19:38 UTC by pritt20

## Description

PR change request to include new parameter `regionendpoint` under s3 registry backend configuration to support IBM COS bucket integration via S3 api.

## Related Issues

https://github.com/astronomer/issues/issues/4853

2022-07-27 21:07 UTC, danielhoherd requested changes
Looks good since it's so small of a change, but I agree with @pgvishnuram that this would be a great opportunity to add tests for `registry.s3Config` behavior entirely. @pritt20 if you need help with that let me know and I can assist.

2022-07-28 12:29 UTC, pritt20 commented
Thanks @danielhoherd and @pgvishnuram !

I have updated the test case as well for this change. Please let me know there are any additional changes :)

2022-07-29 13:27 UTC, danielhoherd approved these changes
LGTM! Thanks for adding the missing tests @pritt20

2022-07-29 13:50 UTC, merged

2022-09-26 07:58 UTC, pgvishnuram commented
@danielhoherd @vishwas-astro this is release as a part of 0.30 can be safely closed