add support for configuring securityContexts on fluentd
astronomer/astronomer pull request #1641
Opened 2022-08-31 15:41 UTC by rob-1126

## Description

Adds a configurable securityContextConstraint for fluentd

## Related Issues

[Github issue #4989](https://github.com/astronomer/issues/issues/4989)

## Testing

Added new unit tests
Tested against a real prod cluster pre-and-post and made sure, when set, the securityContext in pod and container was set appropriately. 

## Merging

Please cherry-pick to main and 0.30.x

2022-08-31 17:02 UTC, pgvishnuram approved these changes

2022-09-06 15:00 UTC, danielhoherd requested changes
Is this going only into release-0.29? If it's going into newer versions too, this should be merged into master and cherry-picked back.

2022-09-06 21:20 UTC, rob-1126 commented
Definitely want it in master and in release-0.30. Will be glad to PR to
master or let you handle, whichever is easiest for you overall.

--Rob

On Tue, Sep 6, 2022 at 11:01 AM Daniel Hoherd ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Is this going only into release-0.29? If it's going into newer versions
> too, this should be merged into master and cherry-picked back.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/astronomer/astronomer/pull/1641#pullrequestreview-1097758858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVHHXBQNRETRU5RA2M7T6WDV45MDDANCNFSM6AAAAAAQBQBNIU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-09 20:44 UTC, merged

2022-09-09 21:03 UTC, danielhoherd commented
Ran into some confusion with this being targeted against 0.29, but eventually got this all sorted out and merged into master, release-0.29 and release-0.30. There were a few merge conflicts.