added task usage data cleanup cron
astronomer/astronomer pull request #1682
Opened 2022-10-07 06:28 UTC by rishkarajgi

## Description

This is a cronjob to hard delete task usage data in houston db older than 90 days

## Related Issues

https://github.com/astronomer/issues/issues/5070

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

0.31.0

2022-10-10 11:12 UTC, pgvishnuram commented on charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
> +  name: houston-cleanup-task-usage-data
can be pre-fixed with release name

2022-10-10 13:40 UTC, danielhoherd commented on charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
> +  name: houston-cleanup-task-usage-data
```suggestion
  name: "{{ .Release.Name }}-houston-cleanup-task-usage-data"
```

2022-10-10 13:49 UTC, danielhoherd commented on charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
> +              # If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.
```suggestion
```

2022-10-10 13:50 UTC, danielhoherd commented on charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
> +  # The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
```suggestion
```

2022-10-10 16:53 UTC, danielhoherd requested changes
Looks good so far. Needs unit tests.

2022-10-12 18:45 UTC, rishkarajgi commented
> Looks good so far. Needs unit tests.

@danielhoherd tests added

cc: @pgvishnuram

2022-10-12 18:52 UTC, pgvishnuram reviewed
unit test cases added to verify the flag

2022-10-12 18:53 UTC, pgvishnuram approved these changes

2022-10-13 15:10 UTC, merged