Adding timeoutSeconds option in the prometheus block #5324
astronomer/astronomer pull request #1776
Opened 2022-12-28 10:04 UTC by shubh-am-kumar

Adding `timeoutSeconds` option in liveness and readiness for the prometheus block in the helm chart to make the value persistent.

Customers are not able to set timeoutSeconds in the prometheus block through the helm.

Request ticket from Walmart:- https://astronomer.zendesk.com/agent/tickets/15098

2022-12-28 16:58 UTC, danielhoherd requested changes
Looking good. Thank you for taking the effort to update the tests! Just need the PR description to be completed and this will be good to merge.

We likely don't need any human testing on this because it will all get caught by unittests and functional tests in CI. This should be safe to merge to all supported branches.

2022-12-28 17:20 UTC, danielhoherd commented on charts/prometheus/values.yaml
> +  timeoutSeconds: 1
```suggestion
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3
```

2022-12-29 06:00 UTC, pgvishnuram approved these changes

2022-12-29 13:29 UTC, danielhoherd approved these changes

2022-12-29 13:31 UTC, merged