add option to allow extraenv in esproxy service
astronomer/astronomer pull request #1857
Opened 2023-04-14 09:09 UTC by pgvishnuram

## Description

Support allowing extraEnv values for es proxy service 

## Related Issues

https://github.com/astronomer/issues/issues/5559
https://github.com/astronomer/issues/issues/5544

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

0.32.0

2023-04-14 09:30 UTC, pgvishnuram commented
test cases pending

2023-04-14 14:29 UTC, rbankston approved these changes
Looks good to me

2023-04-14 20:20 UTC, pgvishnuram commented
@rishkarajgi - Ford was facing some issue with their elasticsearch and they were not able to add proxy to this particular service - so we are now adding this option to allow custom env vars - static test case is pending

2023-04-17 20:33 UTC, danielhoherd commented on tests/chart_tests/test_external_elasticsearch.py
> +        config/values.yaml."""
```suggestion
        """Test External ElasticSearch with secret passed from config/values.yaml."""
```

2023-04-17 20:38 UTC, danielhoherd commented on tests/chart_tests/test_external_elasticsearch.py
> +        assert {"name": "NO_PROXY", "value": "127.0.0.1"} in doc["spec"]["template"][
```suggestion
        assert {"name": "TEST_VAR_NAME", "value": "test_var_value"} in doc["spec"]["template"][
```

2023-04-17 20:39 UTC, danielhoherd requested changes
Code LGTM. PR description needs to be completed.

2023-04-18 18:40 UTC, merged