Relabeling to release for precreatednamespaces
astronomer/astronomer pull request #1887
Opened 2023-05-16 12:08 UTC by rujhan-arora-astronomer

## Description

For pre-created namespaces pods, Relabeling and storing the release names in `release` tag, so that they can be fetched by the query made from houston, under metrics tab

 Related Issues
[4650](https://github.com/astronomer/issues/issues/4650)

## Testing

Kind cluster locally. Also, spinning up a separate cluster

## Merging

0.32.1

2023-05-16 19:03 UTC, danielhoherd requested changes
Seems fine. I discussed with with Vishnu yesterday and it seems like this would be a good solution.

We need tests against prometheus-config-configmap.yaml for this new optional block.

2023-05-17 13:16 UTC, danielhoherd requested changes
@rujhan-arora-astronomer please `pip install pre-commit` and then run `pre-commit install && pre-commit run --all-files` from within the astronomer/astronomer repository and commit the changes.

2023-05-17 14:32 UTC, rujhan-arora-astronomer commented
> pre-commit install && pre-commit run --all-files

Done!

2023-05-17 20:26 UTC, danielhoherd approved these changes
LGTM

2023-05-18 05:09 UTC, rishkarajgi approved these changes

2023-05-18 06:30 UTC, merged