add extraenv support for registry backend service
astronomer/astronomer pull request #1910
Opened 2023-06-06 08:26 UTC by pgvishnuram

## Description

Do not merge this PR until this description is replaced with relevant info.

## Related Issues

Do not merge this PR until this text is replaced with links to related issues.

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

2023-06-06 08:46 UTC, pgvishnuram commented
@danielhoherd

2023-06-06 14:08 UTC, danielhoherd commented on tests/chart_tests/test_astronomer_registry.py
> +    def test_astronomer_registry_statefulset(self, kube_version):
```suggestion
    def test_astronomer_registry_statefulset_defaults(self, kube_version):
```

2023-06-06 14:09 UTC, danielhoherd commented on tests/chart_tests/test_astronomer_registry.py
> +    def test_astronomer_registry_statefulset_with_customenv(self, kube_version):
```suggestion
    def test_astronomer_registry_statefulset_with_custom_env(self, kube_version):
```

2023-06-06 14:12 UTC, danielhoherd commented on tests/chart_tests/test_astronomer_registry.py
> +        ]["spec"]["containers"][0]["env"]
I think something like this is better. I like this pattern we've used elsewhere where we define the object, then include it in the values, and then check for it. This makes it easy to change the object, and ensures it's the same input and output. Also using an env var name that is obviously a test env var will make it easy to spot if we need to debug it.

```suggestion
            extra_env = {"name": "TEST_ENV_VAR_876", "value": "test"}
            values={
                "astronomer": {
                    "registry": {
                        "extraEnv": [extra_env]
                    }
                }
            },
            show_only=[
                "charts/astronomer/templates/registry/registry-statefulset.yaml"
            ],
        )

        assert len(docs) == 1
        doc = docs[0]
        assert doc["kind"] == "StatefulSet"
        assert doc["apiVersion"] == "apps/v1"
        assert doc["metadata"]["name"] == "release-name-registry"
        assert extra_env in doc["spec"]["template"]["spec"]["containers"][0]["env"]
```

2023-06-06 17:26 UTC, danielhoherd requested changes
Code looks great. PR description needs to be completed.

2023-06-07 12:27 UTC, Simpcyclassy commented
can you add the branch it will be cherry-picked to in the description?

2023-06-07 12:33 UTC, merged