sync indexPattern from main config
astronomer/astronomer pull request #1921
Opened 2023-07-04 09:26 UTC by pgvishnuram

## Description

Do not merge this PR until this description is replaced with relevant info.

## Related Issues

https://github.com/astronomer/issues/issues/5594

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

2023-07-05 18:04 UTC, pgvishnuram commented
@rishkarajgi and @danielhoherd

2023-07-05 18:21 UTC, danielhoherd commented on charts/elasticsearch/templates/_helpers.tpl
> +{{- .Values.curator.age.timestring | squote}}
Why do we need "squote" here? We'll definitely need to make test cases with various quoting possibilities. https://helm.sh/docs/chart_template_guide/function_list/#printf may be needed.

2023-07-05 18:21 UTC, danielhoherd reviewed
Looks good. I think that having tests will make it all more clear.

2023-07-06 02:16 UTC, pgvishnuram commented on charts/elasticsearch/templates/curator/es-curator-configmap.yaml
> +          timestring: {{ template "curator.indexPattern" . }}
@danielhoherd it was with single quote thats why i added the same in the helper templates

2023-07-06 05:20 UTC, rishkarajgi approved these changes
lgtm, please address @danielhoherd's comments

2023-07-06 15:10 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +        "image": "quay.io/astronomer/ap-vector:0.22.3",
For test cases we should always set the test to something that is obviously not real data unless parsing is necessary. This makes debugging errors easier.

```suggestion
    image_name = "example.com/some-repo/test-image-name:test-tag-foo"
    indexPattern = "%Y.%m"
    docs = render_chart(
        values={
            "global": {
                "loggingSidecar": {
                    "enabled": True,
                    "name": sidecar_container_name,
                    "image": image_name,
                    "indexPattern": indexPattern,
                }
            }
        },
        show_only=["charts/astronomer/templates/houston/houston-configmap.yaml"],
    )

    common_test_cases(docs)
    doc = docs[0]
    prod_yaml = yaml.safe_load(doc["data"]["production.yaml"])
    log_cmd = 'log_cmd = " 1> >( tee -a /var/log/sidecar-log-consumer/out.log ) 2> >( tee -a /var/log/sidecar-log-consumer/err.log >&2 ) ; "'
    assert (
        log_cmd in prod_yaml["deployments"]["helm"]["airflow"]["airflowLocalSettings"]
    )
    assert prod_yaml["deployments"]["loggingSidecar"] == {
        "enabled": True,
        "name": sidecar_container_name,
        "image": image_name,
```

2023-07-06 15:17 UTC, danielhoherd requested changes
Looks mostly good. I left an optional suggestion to improve a test case. I am also requesting that we parametrize the indexPattern test to make sure `squote` is compatible with index patters that have single quotes. This is highly unlikely to be a real world configuration, but we need to make sure we are properly quoting our data and not making it possible to produce invalid yaml.

2023-07-06 15:36 UTC, pgvishnuram commented on charts/elasticsearch/templates/curator/es-curator-configmap.yaml
> +          timestring: {{ template "curator.indexPattern" . }}
pytest doen;t seems to like % in a string that gets interpolated

2023-07-06 18:08 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +    indexPattern = "%Y.%m"
This parametrize block works and shows that the single-quote val breaks the helm mechanic.
```suggestion
@pytest.mark.parametrize(
    "indexPattern",
    [
        "%Y.%m",
        "%Y.%m.%d",
        "a-single-quote-'-in-the-indexPattern",
        'a-double-quote-"-in-the-indexPattern',
    ],
)
def test_houston_configmap_with_loggingsidecar_enabled_with_indexPattern():
    """Validate the houston configmap and its embedded data with
    loggingSidecar."""
    sidecar_container_name = "sidecar-log-test"
    image_name = "example.com/some-repo/test-image-name:test-tag-foo"
```

2023-07-06 18:10 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +    indexPattern = "%Y.%m"
Another way we could work around this is to add a comment that single-quotes are not allowed. That would be a really easy non-code way to handle this potential problem.

2023-07-06 18:27 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +    indexPattern = "%Y.%m"
I tried to find a way to handle both single and double quotes and I don't see an easy way to do it without making really ugly code. Helm printf does not appear to have any mechanism to produce the right string. I think we can skip merging the parametrize change and just put a comment in the values.yaml that quote characters are not supported in the indexPattern.

2023-07-12 06:17 UTC, pgvishnuram commented
it will require a houston update to pass the indexPattern config

2023-07-13 07:39 UTC, merged