remove uid changes from main config
astronomer/astronomer pull request #1946
Opened 2023-08-03 09:31 UTC by pgvishnuram

## Description

runAsUser in grafana  securityContext creates a constraint in openshift not to run the deployment since the UID range is not in specified range of openshift approved  ones.

## Related Issues

https://github.com/astronomer/issues/issues/5737

## Testing

QA should able to see grafana pod in running status

## Merging

cherry-pick to release-0.32, 0.33

2023-08-03 09:41 UTC, pgvishnuram commented
@danielhoherd @rob-1126

2023-08-03 17:35 UTC, danielhoherd requested changes
Seems fine. Needs tests since this is used in a few places https://github.com/astronomer/astronomer/blob/b2049e2e56/charts/grafana/templates/grafana-deployment.yaml#L50 and there are no securityContext tests in https://github.com/astronomer/astronomer/blob/b2049e2e56/tests/chart_tests/test_grafana.py

2023-08-03 18:04 UTC, pgvishnuram commented
adding test cases

2023-08-04 00:37 UTC, danielhoherd approved these changes
Good improvements on the test with moving them to a class. This all looks good to me.

2023-08-04 04:29 UTC, merged

2023-08-18 03:35 UTC, danielhoherd commented
@pgvishnuram do we want to backport this to 0.30?

2023-08-18 05:49 UTC, pgvishnuram commented
Not needed for 0.30 since this uid change were added from 0.32