add support for custom index name prefix for sidecar logging
astronomer/astronomer pull request #2045
Opened 2023-11-02 11:36 UTC by pgvishnuram

## Description

Do not merge this PR until this description is replaced with relevant info.

## Related Issues

https://github.com/astronomer/issues/issues/5947

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

2023-11-02 13:24 UTC, danielhoherd commented on charts/astronomer/templates/houston/houston-configmap.yaml
> +        indexNamePrefix: {{ .Values.global.loggingSidecar.indexNamePrefix }}
Should we do this as something that works for both fluentd and vector?
```suggestion
        indexNamePrefix: {{ .Values.global.logging.indexNamePrefix }}
```

2023-11-17 12:04 UTC, pgvishnuram commented
we can move this helper function to common template since we are setting defaults to hardcoded values

2023-11-17 13:18 UTC, Simpcyclassy approved these changes
LGTM

2023-11-17 14:25 UTC, danielhoherd commented on charts/external-es-proxy/templates/_helpers.tpl
> +{{- if and .Values.global.loggingSidecar.enabled  -}}
Does this need to be `if and` ?

2023-11-17 14:31 UTC, danielhoherd commented on charts/kibana/templates/_helpers.tpl
> +{{- end -}}
I think this can be simplified with the same code suggestion as external-es-proxy.

2023-11-17 14:36 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +                    "image": "quay.io/astronomer/ap-vector:0.32.2-1",
We should make this test data something that is obviously test data, not something that could be mistaken for valid production values.
```suggestion
                    "image": "quay.io/astronomer/ap-vector:99.88.77",
```

2023-11-17 14:37 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +        "image": "quay.io/astronomer/ap-vector:0.32.2-1",
```suggestion
        "image": "registry.example.com/foobar/test-image-name:99.88.77",
```

2023-11-17 14:38 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +                "logging": {"indexNamePrefix": "astronomer"},
```suggestion
                "logging": {"indexNamePrefix": "test-index-name-prefix-999"},
```

2023-11-17 14:38 UTC, danielhoherd commented on tests/chart_tests/test_houston_configmap.py
> +        "indexNamePrefix": "astronomer",
```suggestion
        "indexNamePrefix": "test-index-name-prefix-999",
```

2023-11-17 14:42 UTC, danielhoherd commented on charts/elasticsearch/templates/_helpers.tpl
> +{{- end -}}
This can probably be simplified with the same changes as the external-es-proxy suggestion.

2023-11-17 14:43 UTC, danielhoherd requested changes
Looks good so far! I left a bunch of suggestions for code improvements and simplification. This is a lot of code to go through so my confidence that I have reviewed it well is not really high, but thankfully there are a lot of tests!

2023-11-17 14:52 UTC, pgvishnuram commented on charts/external-es-proxy/templates/_helpers.tpl
> +{{- if and .Values.global.loggingSidecar.enabled  -}}
and not required

2023-11-17 18:06 UTC, danielhoherd commented on charts/astronomer/templates/_helpers.yaml
> +{{if .Values.global.logging.indexNamePrefix }}{{ .Values.global.logging.indexNamePrefix }}{{- else }}fluentd{{- end -}}
Can we do this not all on one line?

2023-11-17 18:09 UTC, danielhoherd approved these changes
LGTM. I just have one optional suggestion.

2023-11-17 21:11 UTC, merged