add scheduling constraints support
astronomer/astronomer pull request #2344
Opened 2024-10-08 10:55 UTC by pgvishnuram

## Description

Yet to update

## Related Issues

https://github.com/astronomer/issues/issues/6676

## Testing

Yet to update

## Merging

Yet to update

2024-10-08 11:24 UTC, Shubham-astro approved these changes
Added scheduling for jetstream and kibana. looks good

2024-10-08 12:10 UTC, rishkarajgi submitted a review, later dismissed
- PR description needs to be updated
- Add tests

2024-10-10 22:15 UTC, danielhoherd commented on charts/kibana/templates/kibana-default-index-cronjob.yaml
> +{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 10 }}
```suggestion
        nodeSelector: {{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | nindent 10 }}
        affinity: {{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | nindent 10 }}
        tolerations: {{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | nindent 10 }}
```

2024-10-10 22:15 UTC, danielhoherd commented on charts/nats/templates/jetstream-job.yaml
> +{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
```suggestion
      nodeSelector: {{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | nindent 8 }}
      affinity: {{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | nindent 8 }}
      tolerations: {{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | nindent 8 }}
```

2024-10-10 22:16 UTC, danielhoherd requested changes
This all look good so far.

We need test cases that show the scheduling constraints being customized.

2024-10-18 14:26 UTC, danielhoherd commented on charts/prometheus-postgres-exporter/templates/deployment.yaml
> +{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
IMHO we should nindent all of these so they are on a single line. it makes reading the template easier.

2024-10-18 14:29 UTC, danielhoherd commented on tests/chart_tests/test_kibana.py
> +        assert doc["spec"]["template"]["spec"]["nodeSelector"] == {}
We need a test case here to verify that custom nodeSelector, affinity, and tolerations work as expected.

2024-10-18 14:29 UTC, danielhoherd commented on tests/chart_tests/test_nats_jetstream.py
> +        assert docs[7]["spec"]["template"]["spec"]["nodeSelector"] == {}
We need a test case here to verify that custom nodeSelector, affinity, and tolerations work as expected.

2024-10-18 14:30 UTC, danielhoherd requested changes
Looking good. Needs two more test cases, and one test case needs to be renamed and have its docstring updated.

2024-10-18 18:27 UTC, danielhoherd commented on charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
> +      affinity:
These could be nindented.

2024-10-18 18:27 UTC, danielhoherd commented on charts/elasticsearch/templates/curator/es-curator-cronjob.yaml
> +{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 12 }}
These could be nindented

2024-10-21 18:38 UTC, danielhoherd commented on tests/chart_tests/test_elasticsearch.py
> +                "nodeSelector": {"role": "astroelasticsearch"},
If we're going to put global_platform_node_pool_config in __init__.py, shouldn't we deepcopy that and update the fields we need to change?

2024-10-21 18:39 UTC, danielhoherd commented on tests/chart_tests/test_external_elasticsearch.py
> +                "nodeSelector": {"role": "astroesproxy"},
Same deepcopy question here

2024-10-21 18:39 UTC, danielhoherd commented on tests/chart_tests/test_kibana.py
> +                "nodeSelector": {"role": "astrokibana"},
Same deepcopy question here

2024-10-21 18:55 UTC, danielhoherd commented on tests/chart_tests/test_elasticsearch.py
> +        assert c_by_name["curator"]["securityContext"] == {"runAsNonRoot": True}
move `c_by_name = ...` closer to where it is used
```suggestion
        assert docs[0]["kind"] == "CronJob"
        assert docs[0]["metadata"]["name"] == "release-name-elasticsearch-curator"
        assert docs[0]["spec"]["schedule"] == "0 45 * * *"
        assert docs[0]["spec"]["jobTemplate"]["spec"]["template"]["spec"]["nodeSelector"]["role"] == "astro"
        assert len(docs[0]["spec"]["jobTemplate"]["spec"]["template"]["spec"]["affinity"]) == 1
        assert len(docs[0]["spec"]["jobTemplate"]["spec"]["template"]["spec"]["tolerations"]) > 0
        assert (
            docs[0]["spec"]["jobTemplate"]["spec"]["template"]["spec"]["tolerations"]
            == values["global"]["platformNodePool"]["tolerations"]
        )
        c_by_name = get_cronjob_containerspec_by_name(docs[0])
        assert c_by_name["curator"]["command"] == ["/bin/sh", "-c"]
        assert c_by_name["curator"]["args"] == [
            "sleep 5; /usr/bin/curator --config /etc/config/config.yml /etc/config/action_file.yml; exit_code=$?; wget --timeout=5 -O- --post-data='not=used' http://127.0.0.1:15020/quitquitquit; exit $exit_code;"
        ]
        assert c_by_name["curator"]["securityContext"] == {"runAsNonRoot": True}
```

2024-10-21 18:56 UTC, danielhoherd commented on tests/chart_tests/test_elasticsearch.py
> +        assert docs[0]["spec"]["jobTemplate"]["spec"]["template"]["spec"]["nodeSelector"]["role"] == "astroelasticsearch"
nit: With 4 uses, maybe `docs[0]["spec"]["jobTemplate"]["spec"]["template"]["spec"]` should get its own variable?

2024-10-21 18:58 UTC, danielhoherd commented on tests/chart_tests/test_external_elasticsearch.py
> +        assert doc["spec"]["template"]["spec"]["tolerations"] == []
```suggestion
        spec = docs[0]["spec"]["template"]["spec"]
        assert spec["nodeSelector"] == {}
        assert spec["affinity"] == {}
        assert spec["tolerations"] == []
```

2024-10-21 18:59 UTC, danielhoherd commented on tests/chart_tests/test_kibana.py
> +        assert "fluentd.*" in doc["spec"]["template"]["spec"]["containers"][0]["command"][2]
Maybe this?

```suggestion
        spec = docs[0]["spec"]["template"]["spec"]
        assert len(spec["nodeSelector"]) == 1
        assert len(spec["tolerations"]) > 0
        assert spec["tolerations"] == values["global"]["platformNodePool"]["tolerations"]

        assert "fluentd.*" in spec["containers"][0]["command"][2]
```

2024-10-21 19:01 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_blackbox_exporter.py
> +        doc["spec"]["template"]["spec"]["nodeSelector"] == "astro-prometheus-blackbox-exporter"
Is this supposed to be an assignment, not an assertion?

2024-10-21 19:02 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_postgres_exporter.py
> +        assert doc["spec"]["template"]["spec"]["tolerations"] == values["global"]["platformNodePool"]["tolerations"]
```suggestion
        spec = docs[0]["spec"]["template"]["spec"]
        assert len(spec["nodeSelector"]) == 1
        assert len(spec["tolerations"]) > 0
        assert spec["tolerations"] == values["global"]["platformNodePool"]["tolerations"]
```

2024-10-21 19:03 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_postgres_exporter.py
> +        doc["spec"]["template"]["spec"]["nodeSelector"] == "astro-prometheus-postgres-exporter"
This should be an assertion, right?

2024-10-21 19:03 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_postgres_exporter.py
> +        doc = docs[0]
We could do `doc = docs[0]["spec"]["template"]["spec"]` here

2024-10-21 19:04 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_postgres_exporter.py
> +        assert len(docs) == 1
We could do `doc = docs[0]["spec"]["template"]["spec"]` here

2024-10-21 19:04 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_blackbox_exporter.py
> +        doc = docs[0]
We could do `doc = docs[0]["spec"]["template"]["spec"]` here

2024-10-21 19:49 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_postgres_exporter.py
> +        spec["nodeSelector"] == values["prometheus-postgres-exporter"]["nodeSelector"]
This seems wrong. Why is this not an assertion if it is a comparison?

2024-10-21 19:50 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_blackbox_exporter.py
> +        spec["nodeSelector"] == values["prometheus-blackbox-exporter"]["nodeSelector"]
This seems wrong. Why is this not an assertion if it is a comparison?

2024-10-21 19:51 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_blackbox_exporter.py
> +        doc = docs[0]
We dont't need to assign `doc` if we're only going to use it once on the next line. Just use `docs[0]` on the next line.

2024-10-21 19:52 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_blackbox_exporter.py
> +        doc = docs[0]
We dont't need to assign `doc` if we're only going to use it once on the next line. Just use `docs[0]` on the next line.

2024-10-21 19:52 UTC, danielhoherd commented on tests/chart_tests/test_prometheus_blackbox_exporter.py
> +        assert doc["spec"]["template"]["spec"]["nodeSelector"] == {}
We could do the spec assignment here to make this shorter.

2024-10-21 19:53 UTC, danielhoherd commented on tests/chart_tests/test_kibana.py
> +        doc["spec"]["template"]["spec"]["nodeSelector"] == "astrokibana"
Why is this comparison not an assertion?

2024-10-21 19:54 UTC, danielhoherd commented on tests/chart_tests/test_kibana.py
> +        doc = docs[0]
We could do the `spec = docs[0]['spec']['template']['spec']` thing here.

2024-10-21 19:54 UTC, danielhoherd commented on tests/chart_tests/test_kibana.py
> +        assert doc["spec"]["template"]["spec"]["nodeSelector"] == {}
We could do the `spec = docs[0]['spec']['template']['spec']` thing here.

2024-10-21 19:57 UTC, danielhoherd commented on tests/chart_tests/test_external_elasticsearch.py
> +        and tolerations with global config and nginx defaults"""
```suggestion
        and tolerations with global config and nginx overrides."""
```

2024-10-21 19:58 UTC, danielhoherd commented on tests/chart_tests/test_external_elasticsearch.py
> +        and tolerations with global config and nginx defaults"""
```suggestion
        and tolerations with global config and nginx overrides"""
```

2024-10-21 20:02 UTC, danielhoherd commented on tests/chart_tests/test_elasticsearch.py
> +        """Test ElasticSearch Curator cron job with nodeSelector, affinity, tolerations and config defaults"""
```suggestion
        """Test ElasticSearch Curator cron job with nodeSelector, affinity, tolerations and config overrides."""
```

2024-10-21 20:02 UTC, danielhoherd commented on tests/chart_tests/test_elasticsearch.py
> +        """Test ElasticSearch Curator cron job with nodeSelector, affinity, tolerations and config defaults"""
```suggestion
        """Test ElasticSearch Curator cron job with nodeSelector, affinity, tolerations and config overrides."""
```

2024-10-22 13:13 UTC, danielhoherd commented on tests/chart_tests/test_stan_sts.py
> +        assert spec["tolerations"] == []
We should replace the values on line 96 in this file with global_platform_node_pool_config

2024-10-22 13:17 UTC, danielhoherd approved these changes
Lots of new code, but after a bunch of back and forth I think this looks great.

I left one more optional improvement to replace prior test values with global_platform_node_pool_config

2024-10-22 14:34 UTC, merged