add default backend configurable flag support
astronomer/astronomer pull request #2407
Opened 2024-11-12 08:52 UTC by pgvishnuram

## Description

Do not merge this PR until this description is replaced with relevant info.

## Related Issues

- https://github.com/astronomer/issues/issues/6748

## Testing

Do not merge this PR until this text is replaced with details about how these changes were tested.

## Merging

Do not merge this PR until it lists which release branches this PR should be merged / cherry-picked into.

2024-11-12 19:50 UTC, danielhoherd commented on charts/nginx/templates/nginx-default-backend-networkpolicy.yaml
> +{{- if and .Values.defaultBackend.enabled  .Values.global.networkPolicy.enabled }}
```suggestion
{{- if and .Values.defaultBackend.enabled .Values.global.networkPolicy.enabled }}
```

2024-11-12 19:50 UTC, danielhoherd commented on charts/nginx/templates/nginx-default-backend-pod-disruption-budget.yaml
> +{{- if and .Values.defaultBackend.enabled  .Values.global.podDisruptionBudgetsEnabled }}
```suggestion
{{- if and .Values.defaultBackend.enabled .Values.global.podDisruptionBudgetsEnabled }}
```

2024-11-12 19:50 UTC, danielhoherd commented on charts/nginx/templates/nginx-default-backend-serviceaccount.yaml
> +{{- if and .Values.defaultBackend.enabled  .Values.global.rbacEnabled }}
```suggestion
{{- if and .Values.defaultBackend.enabled .Values.global.rbacEnabled }}
```

2024-11-14 06:28 UTC, rishkarajgi requested changes
needs tests

2024-11-14 06:36 UTC, rishkarajgi approved these changes

2024-11-14 06:50 UTC, merged