add configmap names support for airflow  runtime version
astronomer/astronomer pull request #2449
Opened 2024-12-09 06:19 UTC by pgvishnuram

## Description

This PR implements a change to include config name support to mount volume and volume mounts automatically by providing a file name 

## Related Issues

- https://github.com/astronomer/issues/issues/6680

## Testing

QA should able to provide pre-created configmap with runtime and airflow versions list

## Merging

cherry-pick to release-0.36 , release-0.37

2024-12-09 07:23 UTC, rishkarajgi commented on charts/astronomer/templates/_helpers.yaml
> +{{ if and .Values.houston.airflowReleasesConfig ( not .Values.houston.airflowReleasesconfigMapName ) }}
```suggestion
{{ if and .Values.houston.airflowReleasesConfig ( not .Values.houston.airflowReleasesConfigMapName ) }}
```

2024-12-09 07:23 UTC, rishkarajgi commented on charts/astronomer/templates/_helpers.yaml
> +{{ if and .Values.houston.airflowReleasesConfig ( not .Values.houston.airflowReleasesconfigMapName ) }}
please maintain camel case

2024-12-09 07:23 UTC, rishkarajgi commented on charts/astronomer/values.yaml
> +  airflowReleasesconfigMapName: ~
```suggestion
  airflowReleasesConfigMapName: ~
```

2024-12-09 07:23 UTC, rishkarajgi commented on charts/astronomer/values.yaml
> +  runtimeReleasesconfigMapName: ~
```suggestion
  runtimeReleasesConfigMapName: ~
```

2024-12-09 07:24 UTC, rishkarajgi requested changes
please add tests

2024-12-11 20:48 UTC, danielhoherd commented on charts/astronomer/values.yaml
>    RuntimeReleasesConfig:
This should be lowercase R
```suggestion
  runtimeReleasesConfig:
```

2024-12-16 08:08 UTC, Shubham-astro approved these changes
Looks good

2024-12-16 16:22 UTC, danielhoherd commented on tests/chart_tests/test_houston_api_deployment.py
> +        ."""
```suggestion
        """Validate that houston configmap and its embedded data with runtime and airflow configmap name defined."""
```

2024-12-16 16:26 UTC, danielhoherd commented on charts/astronomer/templates/_helpers.yaml
> +    name: {{ .Values.houston.airflowReleasesConfigMapName  }}
```suggestion
    name: {{ .Values.houston.airflowReleasesConfigMapName }}
```

2024-12-16 16:26 UTC, danielhoherd commented on charts/astronomer/templates/_helpers.yaml
> +{{- if .Values.houston.airflowReleasesConfigMapName  }}
```suggestion
{{- if .Values.houston.airflowReleasesConfigMapName }}
```

2024-12-16 18:23 UTC, merged