bypass database creation when manual connection is added
astronomer/astronomer pull request #2455
Opened 2024-12-20 05:57 UTC by pgvishnuram

## Description
bypass database creation when manual connection is added

## Related Issues

Yet to update

## Testing

Yet to update

## Merging

Yet to update

2024-12-30 18:04 UTC, pgvishnuram commented
@danielhoherd

2025-01-06 18:20 UTC, danielhoherd commented on tests/chart_tests/test_grafana.py
> +            values={"grafana": {"backendSecretName": "grafanabackend"}},
We don't appear to have any tests that ensure `backendSecretName` is working the way we expect it to.

2025-01-06 18:22 UTC, danielhoherd commented on tests/chart_tests/test_astronomer_houston_hook_job.py
> +    def test_db_migration_job_init_containers_disabled_with_custom_secret_name(self, kube_version):
We don't appear to have any tests that `airflowBackendSecretName` or `backendSecretName` function how we expect them to. We only have these tests for the initContainer.

2025-01-06 18:22 UTC, danielhoherd requested changes
This looks good so far, but we are missing some tests.

2025-01-07 16:32 UTC, danielhoherd commented on tests/chart_tests/test_houston_api_deployment.py
> +        env_vars = {x["name"]: x.get("value") if "value" in x else x.get("valueFrom") for x in c_by_name["houston"]["env"]}
```suggestion
        env_vars = {x["name"]: x.get("value", x.get("valueFrom")) for x in c_by_name["houston"]["env"]}
```

2025-01-07 16:34 UTC, danielhoherd commented on tests/chart_tests/test_astronomer_houston_hook_job.py
> +        env_vars = {x["name"]: x.get("value") if "value" in x else x.get("valueFrom") for x in c_by_name["post-upgrade-job"]["env"]}
Same optional suggestion as below

2025-01-07 16:35 UTC, danielhoherd commented on tests/chart_tests/test_astronomer_houston_hook_job.py
> +        env_vars = {x["name"]: x.get("value") if "value" in x else x.get("valueFrom") for x in c_by_name["post-upgrade-job"]["env"]}
Same optional suggestion as below

2025-01-07 16:36 UTC, danielhoherd commented on tests/chart_tests/test_houston_api_deployment.py
> +        """Test houston Deployments Init Containers  disabled when custom houston secret name is passed."""
Whitespace
```suggestion
        """Test houston Deployments Init Containers disabled when custom houston secret name is passed."""
```

2025-01-07 16:38 UTC, danielhoherd approved these changes
Looks good. I left some optional suggestions.

2025-01-07 17:32 UTC, merged

2025-03-05 20:59 UTC, danielhoherd commented
Cherry-picking this to release-0.34 is causing a lot of conflicts that are not easy to work through. I am going to skip it for now.